#!/usr/bin/env bash
# iNTRUDER v1.5 - Sudo Permissions Setup Script
# This script configures passwordless sudo access for the tools needed by the intruder service.
set -euo pipefail

SERVICE_USER="intruder"
SUDOERS_FILE="/etc/sudoers.d/intruder-permissions"

# Check for root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

echo "--- Configuring Sudo Permissions for user '$SERVICE_USER' ---"

# Find the full paths of the required commands
echo "[+] Locating required pentesting tools..."
AIRMON_NG_PATH=$(which airmon-ng)
AIRODUMP_NG_PATH=$(which airodump-ng)
AIREPLAY_NG_PATH=$(which aireplay-ng)
AIRCRACK_NG_PATH=$(which aircrack-ng)
MDK4_PATH=$(which mdk4)
REAVER_PATH=$(which reaver)
HPING3_PATH=$(which hping3)
SERVICE_PATH=$(which service)
IW_PATH=$(which iw)

# Check if all tools were found
for tool_path in $AIRMON_NG_PATH $AIRODUMP_NG_PATH $AIREPLAY_NG_PATH $AIRCRACK_NG_PATH $MDK4_PATH $REAVER_PATH $HPING3_PATH $SERVICE_PATH $IW_PATH; do
    if [ ! -x "$tool_path" ]; then
        echo "Error: Command not found or not executable: $tool_path"
        echo "Please ensure all dependencies are installed correctly before running this script."
        exit 1
    fi
done

echo "[+] Creating sudoers configuration file at $SUDOERS_FILE"

# Create the sudoers file with the necessary permissions
# Using NOPASSWD is required for a background service that cannot prompt for a password.
# This is carefully scoped to only the commands needed.
(
cat <<EOF
# Sudo permissions for the iNTRUDER service user
# This file was automatically generated by setup_permissions.sh

# Allow the 'intruder' user to run specific pentesting tools without a password.
$SERVICE_USER ALL=(ALL) NOPASSWD: $AIRMON_NG_PATH
$SERVICE_USER ALL=(ALL) NOPASSWD: $AIRODUMP_NG_PATH
$SERVICE_USER ALL=(ALL) NOPASSWD: $AIREPLAY_NG_PATH
$SERVICE_USER ALL=(ALL) NOPASSWD: $AIRCRACK_NG_PATH
$SERVICE_USER ALL=(ALL) NOPASSWD: $MDK4_PATH
$SERVICE_USER ALL=(ALL) NOPASSWD: $REAVER_PATH
$SERVICE_USER ALL=(ALL) NOPASSWD: $HPING3_PATH
$SERVICE_USER ALL=(ALL) NOPASSWD: $SERVICE_PATH NetworkManager *
$SERVICE_USER ALL=(ALL) NOPASSWD: $IW_PATH dev * set type *
EOF
) > $SUDOERS_FILE

# Set correct permissions for the sudoers file
chmod 0440 $SUDOERS_FILE

echo ""
echo "--- Sudo Permissions Configured Successfully ---"
echo "User '$SERVICE_USER' can now run the required commands with sudo privileges."
echo "You may now start the intruder service: sudo systemctl start intruder"
