# monitoring/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules.yml'

scrape_configs:
  - job_name: 'nexus-server'
    static_configs:
      - targets: ['nexus-server:8443'] # Assuming an /metrics endpoint is exposed
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']